# ── App Name ──────────────────────────────────────────────
spring.application.name=ipr

# ── Server Port ───────────────────────────────────────────
#server.port=8080

# ── Database Connection ───────────────────────────────────
spring.datasource.url=jdbc:postgresql://dpg-d8tt20flk1mc73c2c52g-a/ipr_3oad
spring.datasource.username=ipr_3oad_user
spring.datasource.password=xKr1Hs368o8sHdaVocrPehSNyDM8oEzV

# ── JPA / Hibernate ───────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ── Error Messages ────────────────────────────────────────
spring.web.error.include-message=always

# ── Connection Pool (HikariCP) ────────────────────────────
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000